In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/exoplanets.csv", comment="#")

In [4]:
df.head()

,pl_name,hostname,default_flag,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,soltype,pl_controv_flag,...,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,rowupdate,pl_pubdate,releasedate
0,11 Com b,11 Com,1,2,1,Radial Velocity,2007,Xinglong Station,Published Confirmed,0,...,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848,2023-09-19,2023-12,2023-09-19
1,11 Com b,11 Com,0,2,1,Radial Velocity,2007,Xinglong Station,Published Confirmed,0,...,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848,2014-05-14,2008-01,2014-05-14
2,11 Com b,11 Com,0,2,1,Radial Velocity,2007,Xinglong Station,Published Confirmed,0,...,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848,2014-07-23,2011-08,2014-07-23
3,11 UMi b,11 UMi,1,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,Published Confirmed,0,...,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903,2018-09-04,2017-03,2018-09-06
4,11 UMi b,11 UMi,0,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,Published Confirmed,0,...,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903,2018-04-25,2011-08,2014-07-23

In [5]:
df.shape

(39978, 92)

Dataset contains:
- 39978 planets
- 92 features

In [6]:
df.columns

Index(['pl_name', 'hostname', 'default_flag', 'sy_snum', 'sy_pnum',
       'discoverymethod', 'disc_year', 'disc_facility', 'soltype',
       'pl_controv_flag', 'pl_refname', 'pl_orbper', 'pl_orbpererr1',
       'pl_orbpererr2', 'pl_orbperlim', 'pl_orbsmax', 'pl_orbsmaxerr1',
       'pl_orbsmaxerr2', 'pl_orbsmaxlim', 'pl_rade', 'pl_radeerr1',
       'pl_radeerr2', 'pl_radelim', 'pl_radj', 'pl_radjerr1', 'pl_radjerr2',
       'pl_radjlim', 'pl_bmasse', 'pl_bmasseerr1', 'pl_bmasseerr2',
       'pl_bmasselim', 'pl_bmassj', 'pl_bmassjerr1', 'pl_bmassjerr2',
       'pl_bmassjlim', 'pl_bmassprov', 'pl_orbeccen', 'pl_orbeccenerr1',
       'pl_orbeccenerr2', 'pl_orbeccenlim', 'pl_insol', 'pl_insolerr1',
       'pl_insolerr2', 'pl_insollim', 'pl_eqt', 'pl_eqterr1', 'pl_eqterr2',
       'pl_eqtlim', 'ttv_flag', 'st_refname', 'st_spectype', 'st_teff',
       'st_tefferr1', 'st_tefferr2', 'st_tefflim', 'st_rad', 'st_raderr1',
       'st_raderr2', 'st_radlim', 'st_mass', 'st_masserr1', 'st_masserr2',
       'st_masslim', 'st_met', 'st_meterr1', 'st_meterr2', 'st_metlim',
       'st_metratio', 'st_logg', 'st_loggerr1', 'st_loggerr2', 'st_logglim',
       'sy_refname', 'rastr', 'ra', 'decstr', 'dec', 'sy_dist', 'sy_disterr1',
       'sy_disterr2', 'sy_vmag', 'sy_vmagerr1', 'sy_vmagerr2', 'sy_kmag',
       'sy_kmagerr1', 'sy_kmagerr2', 'sy_gaiamag', 'sy_gaiamagerr1',
       'sy_gaiamagerr2', 'rowupdate', 'pl_pubdate', 'releasedate'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39978 entries, 0 to 39977
Data columns (total 92 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          39978 non-null  str
 1   hostname         39978 non-null  str
 2   default_flag     39978 non-null  int64
 3   sy_snum          39978 non-null  int64
 4   sy_pnum          39978 non-null  int64
 5   discoverymethod  39978 non-null  str
 6   disc_year        39978 non-null  int64
 7   disc_facility    39978 non-null  str
 8   soltype          39978 non-null  str
 9   pl_controv_flag  39978 non-null  int64
 10  pl_refname       39978 non-null  str
 11  pl_orbper        36585 non-null  float64
 12  pl_orbpererr1    34874 non-null  float64
 13  pl_orbpererr2    34873 non-null  float64
 14  pl_orbperlim     36585 non-null  float64
 15  pl_orbsmax       22308 non-null  float64
 16  pl_orbsmaxerr1   7833 non-null   float64
 17  pl_orbsmaxerr2   7832 non-null   float64
 18  pl_orbsmaxlim    25095 non-null  float64
 19  pl_rade          27549 non-null  float64
 20  pl_radeerr1      26803 non-null  float64
 21  pl_radeerr2      26803 non-null  float64
 22  pl_radelim       30295 non-null  float64
 23  pl_radj          27549 non-null  float64
 24  pl_radjerr1      26803 non-null  float64
 25  pl_radjerr2      26803 non-null  float64
 26  pl_radjlim       27549 non-null  float64
 27  pl_bmasse        7486 non-null   float64
 28  pl_bmasseerr1    6813 non-null   float64
 29  pl_bmasseerr2    6813 non-null   float64
 30  pl_bmasselim     7486 non-null   float64
 31  pl_bmassj        7485 non-null   float64
 32  pl_bmassjerr1    6807 non-null   float64
 33  pl_bmassjerr2    6807 non-null   float64
 34  pl_bmassjlim     7485 non-null   float64
 35  pl_bmassprov     7486 non-null   str
 36  pl_orbeccen      19025 non-null  float64
 37  pl_orbeccenerr1  3955 non-null   float64
 38  pl_orbeccenerr2  3954 non-null   float64
 39  pl_orbeccenlim   21769 non-null  float64
 40  pl_insol         17347 non-null  float64
 41  pl_insolerr1     15862 non-null  float64
 42  pl_insolerr2     15862 non-null  float64
 43  pl_insollim      22407 non-null  float64
 44  pl_eqt           17541 non-null  float64
 45  pl_eqterr1       2712 non-null   float64
 46  pl_eqterr2       2712 non-null   float64
 47  pl_eqtlim        20285 non-null  float64
 48  ttv_flag         39944 non-null  float64
 49  st_refname       39534 non-null  str
 50  st_spectype      3102 non-null   str
 51  st_teff          36342 non-null  float64
 52  st_tefferr1      35386 non-null  float64
 53  st_tefferr2      35126 non-null  float64
 54  st_tefflim       36342 non-null  float64
 55  st_rad           36536 non-null  float64
 56  st_raderr1       30831 non-null  float64
 57  st_raderr2       30678 non-null  float64
 58  st_radlim        36536 non-null  float64
 59  st_mass          33485 non-null  float64
 60  st_masserr1      28053 non-null  float64
 61  st_masserr2      27898 non-null  float64
 62  st_masslim       33492 non-null  float64
 63  st_met           25031 non-null  float64
 64  st_meterr1       24356 non-null  float64
 65  st_meterr2       24356 non-null  float64
 66  st_metlim        27343 non-null  float64
 67  st_metratio      24834 non-null  str
 68  st_logg          30974 non-null  float64
 69  st_loggerr1      25518 non-null  float64
 70  st_loggerr2      25517 non-null  float64
 71  st_logglim       30974 non-null  float64
 72  sy_refname       39941 non-null  str
 73  rastr            39941 non-null  str
 74  ra               39941 non-null  float64
 75  decstr           39941 non-null  str
 76  dec              39941 non-null  float64
 77  sy_dist          39087 non-null  float64
 78  sy_disterr1      38224 non-null  float64
 79  sy_disterr2      38224 non-null  float64
 80  sy_vmag          39095 non-null  float64
 81  sy_vmagerr1      39082 non-null  float64
 82  sy_vmagerr2      39081 non-null  float64
 83  sy_kmag          39090 non-null  float64
 84  sy_kmagerr1      38848 non-null  float64
 85  sy_kmagerr2      38848 non-null  float64
 86  sy_gaiamag       38797 non-null  float64
 87  sy_gaiamagerr1   38797 non-null  float64
 88  sy_gaiamagerr2   38797 non-null  float64
 89  rowupdate        39940 non-null  str
 90  pl_pubdate       39941 non-null  str
 91  releasedate      39941 non-null  str
dtypes: float64(71), int64(5), str(16)
memory usage: 28.1 MB

In [8]:
df.describe()

,default_flag,sy_snum,sy_pnum,disc_year,pl_controv_flag,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
count,39978.000000,39978.000000,39978.000000,39978.000000,39978.000000,3.658500e+04,3.487400e+04,3.487300e+04,36585.000000,22308.000000,...,38224.000000,39095.000000,39082.000000,39081.000000,39090.000000,38848.000000,38848.000000,38797.000000,38797.000000,38797.000000
mean,0.158062,1.086247,1.917179,2015.648457,0.004052,1.196728e+04,1.383424e+04,-3.261216e+03,-0.000246,4.756123,...,-38.650119,13.507641,0.114867,-0.115441,11.475592,0.034939,-0.034467,13.269426,0.000524,-0.000524
std,0.364804,0.312204,1.239174,4.151812,0.063529,2.102939e+06,2.516972e+06,5.367294e+05,0.020247,179.637112,...,184.629691,2.459873,0.149318,0.178163,2.369353,0.183614,0.175095,2.400611,0.001092,0.001092
min,0.000000,1.000000,1.000000,1992.000000,0.000000,9.070629e-02,0.000000e+00,-1.000000e+08,-1.000000,0.004400,...,-2900.000000,0.872000,0.001000,-12.270000,-3.044000,0.011000,-11.140000,2.364310,0.000112,-0.063232
25%,0.000000,1.000000,1.000000,2014.000000,0.000000,4.370332e+00,8.078725e-06,-2.012000e-04,0.000000,0.054600,...,-20.190000,12.444000,0.046000,-0.137000,10.550000,0.020000,-0.033000,12.226900,0.000254,-0.000508
50%,0.000000,1.000000,1.000000,2016.000000,0.000000,1.030401e+01,3.831500e-05,-3.838000e-05,0.000000,0.101500,...,-7.216500,14.127000,0.092000,-0.092000,12.208000,0.024000,-0.024000,13.924300,0.000353,-0.000353
75%,0.000000,1.000000,2.000000,2016.000000,0.000000,2.654851e+01,2.013000e-04,-8.087000e-06,0.000000,0.223025,...,-1.896000,15.242000,0.137000,-0.046000,13.135000,0.033000,-0.020000,15.019100,0.000508,-0.000254
max,1.000000,4.000000,8.000000,2026.000000,1.000000,4.020000e+08,4.700000e+08,0.000000e+00,1.000000,19000.000000,...,2700.000000,45.340000,11.000000,-0.001000,35.330000,9.995000,-0.011000,20.186100,0.063232,-0.000112

In [9]:
df.isnull().sum()

pl_name              0
hostname             0
default_flag         0
sy_snum              0
sy_pnum              0
                  ...
sy_gaiamagerr1    1181
sy_gaiamagerr2    1181
rowupdate           38
pl_pubdate          37
releasedate         37
Length: 92, dtype: int64

In [10]:
df.duplicated().sum()

np.int64(56)