### Phase 3a - Data Quality Assessment

In [32]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv("../data/interim/planet_master.csv")

In [34]:
df.head()

,pl_name,hostname,discoverymethod,disc_year,pl_orbper,pl_rade,pl_bmasse,pl_eqt,st_teff,st_rad,st_mass,sy_dist,ra,dec
0,11 Com b,11 Com,Radial Velocity,2007,323.21000,NaN,4914.898486,NaN,4874.0,13.76,2.09,93.1846,185.178779,17.793252
1,11 Com b,11 Com,Radial Velocity,2007,326.03000,NaN,6165.600000,NaN,4742.0,19.00,2.70,93.1846,185.178779,17.793252
2,11 Com b,11 Com,Radial Velocity,2007,NaN,NaN,5434.700000,NaN,NaN,NaN,2.60,93.1846,185.178779,17.793252
3,11 UMi b,11 UMi,Radial Velocity,2009,516.21997,NaN,4684.814200,NaN,4213.0,29.79,2.78,125.3210,229.274595,71.823943
4,11 UMi b,11 UMi,Radial Velocity,2009,NaN,NaN,3432.400000,NaN,NaN,NaN,1.70,125.3210,229.274595,71.823943

In [35]:
df.shape

(39978, 14)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39978 entries, 0 to 39977
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          39978 non-null  str
 1   hostname         39978 non-null  str
 2   discoverymethod  39978 non-null  str
 3   disc_year        39978 non-null  int64
 4   pl_orbper        36585 non-null  float64
 5   pl_rade          27549 non-null  float64
 6   pl_bmasse        7486 non-null   float64
 7   pl_eqt           17541 non-null  float64
 8   st_teff          36342 non-null  float64
 9   st_rad           36536 non-null  float64
 10  st_mass          33485 non-null  float64
 11  sy_dist          39087 non-null  float64
 12  ra               39941 non-null  float64
 13  dec              39941 non-null  float64
dtypes: float64(10), int64(1), str(3)
memory usage: 4.3 MB

In [37]:
df.duplicated().sum()

np.int64(5554)

In [38]:
df = df.drop_duplicates()

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
missing = df.isnull().sum()

missing

pl_name                0
hostname               0
discoverymethod        0
disc_year              0
pl_orbper           3253
pl_rade            12272
pl_bmasse          27068
pl_eqt             22255
st_teff             3498
st_rad              3297
st_mass             6474
sy_dist              725
ra                    36
dec                   36
dtype: int64

In [41]:
missing = (df.isnull().sum() / len(df)) * 100
missing.sort_values(ascending=False)

pl_bmasse          78.631188
pl_eqt             64.649663
pl_rade            35.649547
st_mass            18.806647
st_teff            10.161515
st_rad              9.577620
pl_orbper           9.449802
sy_dist             2.106089
ra                  0.104578
dec                 0.104578
discoverymethod     0.000000
disc_year           0.000000
pl_name             0.000000
hostname            0.000000
dtype: float64

In [46]:
df = df.rename(columns={
    "pl_name":"planet_name",
    "hostname":"host_star",
    "discoverymethod":"discovery_method",
    "disc_year":"discovery_year",
    "pl_orbper":"orbital_period_days",
    "pl_rade":"planet_radius_earth",
    "pl_bmasse":"planet_mass_earth",
    "pl_eqt":"equilibrium_temperature",
    "st_teff":"star_temperature",
    "st_rad":"star_radius",
    "st_mass":"star_mass",
    "sy_dist":"distance_pc",
    "ra":"right_ascension",
    "dec":"declination"
})

In [47]:
df.columns

Index(['planet_name', 'host_star', 'discovery_method', 'discovery_year',
       'orbital_period_days', 'planet_radius_earth', 'planet_mass_earth',
       'equilibrium_temperature', 'star_temperature', 'star_radius',
       'star_mass', 'distance_pc', 'right_ascension', 'declination'],
      dtype='str')

In [48]:
df.dtypes

planet_name                    str
host_star                      str
discovery_method               str
discovery_year               int64
orbital_period_days        float64
planet_radius_earth        float64
planet_mass_earth          float64
equilibrium_temperature    float64
star_temperature           float64
star_radius                float64
star_mass                  float64
distance_pc                float64
right_ascension            float64
declination                float64
dtype: object

In [49]:
(df["planet_radius_earth"] <= 0).sum()

np.int64(0)

In [50]:
(df["planet_mass_earth"] <= 0).sum()

np.int64(0)

In [51]:
(df["equilibrium_temperature"] <= 0).sum()

np.int64(0)

In [52]:
(df["orbital_period_days"] <= 0).sum()

np.int64(0)

In [22]:
df["discovery_method"].value_counts()

discovery_method
Transit                          30430
Radial Velocity                   2935
Microlensing                       664
Imaging                            190
Transit Timing Variations          138
Eclipse Timing Variations           26
Orbital Brightness Modulation       19
Pulsar Timing                       13
Astrometry                           6
Pulsation Timing Variations          2
Disk Kinematics                      1
Name: count, dtype: int64

In [23]:
df["discovery_year"].describe()

count    34424.000000
mean      2015.579421
std          4.327112
min       1992.000000
25%       2014.000000
50%       2016.000000
75%       2016.000000
max       2026.000000
Name: discovery_year, dtype: float64

In [24]:
df["discovery_year"].value_counts().sort_index()

discovery_year
1992        6
1994        2
1995        6
1996       45
1997        6
1998       43
1999       83
2000       83
2001       68
2002      153
2003       92
2004      185
2005      168
2006      156
2007      340
2008      331
2009      425
2010      609
2011     1043
2012     1121
2013      976
2014     8205
2015      909
2016    10932
2017      598
2018     1002
2019      577
2020      859
2021     2358
2022      762
2023      925
2024      557
2025      420
2026      379
Name: count, dtype: int64

In [53]:
df.to_csv("../data/processed/clean_planet_data.csv", index=False)

### Phase 3B – Missing Value Strategy

In [54]:
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing %": (df.isnull().sum() / len(df)) * 100
})

missing.sort_values("Missing %", ascending=False)

                         Missing Count  Missing %
planet_mass_earth                27068  78.631188
equilibrium_temperature          22255  64.649663
planet_radius_earth              12272  35.649547
star_mass                         6474  18.806647
star_temperature                  3498  10.161515
star_radius                       3297   9.577620
orbital_period_days               3253   9.449802
distance_pc                        725   2.106089
right_ascension                     36   0.104578
declination                         36   0.104578
discovery_method                     0   0.000000
discovery_year                       0   0.000000
planet_name                          0   0.000000
host_star                            0   0.000000

In [55]:
essential_columns = [
    "planet_name",
    "host_star",
    "discovery_method",
    "discovery_year"
]

important_columns = [
    "planet_radius_earth",
    "orbital_period_days",
    "star_temperature",
    "star_radius",
    "star_mass",
    "distance_pc"
]

optional_columns = [
    "planet_mass_earth",
    "equilibrium_temperature",
    "right_ascension",
    "declination"
]

In [56]:
print(df[essential_columns].isnull().sum())

planet_name         0
host_star           0
discovery_method    0
discovery_year      0
dtype: int64

In [57]:
print(df[important_columns].isnull().sum())

planet_radius_earth    12272
orbital_period_days     3253
star_temperature        3498
star_radius             3297
star_mass               6474
distance_pc              725
dtype: int64

In [58]:
print(df[optional_columns].isnull().sum())

planet_mass_earth          27068
equilibrium_temperature    22255
right_ascension               36
declination                   36
dtype: int64

### Missing Value Strategy

- Essential columns: Must not contain missing values.
- Important columns: Keep missing values for now; they may be filtered for specific analyses or models.
- Optional columns: Retain missing values because they represent measurements that have not yet been observed, not data entry errors.

In [59]:
df.to_csv("../data/processed/clean_planet_data.csv", index=False)